all: compile
	@echo -e '[INFO] Done!'

clean: 
	@echo -e '[INFO] Cleaning up...'
	@-rm -rf cs455/overlay/*/*.class

compile:
	@echo -e '[INFO] Compiling the Source...'
	@javac -d . cs455/overlay/*/*.java